model:
  base_name: cnn_v04
  batchsize: 64
  epochs: 3000
  lr: 0.005
  lr_decay: true
  lr_gamma: 0.2
  lr_milestones: 
  - 1000
  conv_channels:
  - 16
  - 32
  - 64
  downsample:
  - true
  - true
  - true
  global_maxpool: true
  linear_features:
  - 200
  - 100
  - 20
  device: cuda
data:
  cube_key: 'lightcones/brightness_temp'
  label_key: 'lightcone_params/physparams'
  zlength: 30
  boxlength: 256
  param_index: 1
  wedgeslope: 0.0
